(function(root){
  const PROMPT_VERSION='signal-v2.4-scoring';
  const SCORE_KEYS=['compositionScore','subjectPreservationScore','cleanupQualityScore','distractionRemovalScore','aestheticScore','platformSuitabilityScore','technicalConfidenceScore'];
  const BRAND_KEY='brandConsistencyScore';
  const WEIGHTS={compositionScore:.15,subjectPreservationScore:.18,cleanupQualityScore:.14,distractionRemovalScore:.13,aestheticScore:.14,platformSuitabilityScore:.14,brandConsistencyScore:.08,technicalConfidenceScore:.12};
  const SECRET_PATTERNS=[/sk-[a-z0-9_-]+/ig,/api[_-]?key\s*[:=]\s*[^\s,;]+/ig,/token\s*[:=]\s*[^\s,;]+/ig,/secret\s*[:=]\s*[^\s,;]+/ig];
  function hasBrand(ctx){return !!(ctx&&(ctx.brandProfile||ctx.profileSnapshot||ctx.brandProfileAttached||ctx.profileId));}
  function clone(v){return JSON.parse(JSON.stringify(v));}
  function clean(v){return String(v==null?'':v).trim();}
  function clamp(v){const n=Math.round(Number(v));return Number.isFinite(n)?Math.max(0,Math.min(100,n)):null;}
  function inputScore(option){const s=option&&option.signalScore||option&&option.score||null;if(!s||typeof s!=='object')return null;return s;}
  function mapLegacy(s){return {compositionScore:s.compositionScore??s.composition,subjectPreservationScore:s.subjectPreservationScore??s.subjectPreservation,cleanupQualityScore:s.cleanupQualityScore??s.technicalQuality,distractionRemovalScore:s.distractionRemovalScore??s.generativeConfidence,aestheticScore:s.aestheticScore??s.composition,platformSuitabilityScore:s.platformSuitabilityScore??s.platformFit,brandConsistencyScore:s.brandConsistencyScore,technicalConfidenceScore:s.technicalConfidenceScore??s.technicalQuality,overallScore:s.overallScore??s.overall};}
  function computeOverall(score,brandAttached){let total=0,wtotal=0;Object.keys(WEIGHTS).forEach(k=>{if(k===BRAND_KEY&&!brandAttached)return;const n=score[k];if(Number.isFinite(n)){total+=n*WEIGHTS[k];wtotal+=WEIGHTS[k];}});return wtotal?clamp(total/wtotal):null;}
  function normalizeReport(report){report=report&&typeof report==='object'?report:{};return{removedItems:Array.isArray(report.removedItems)?report.removedItems.map(clean).filter(Boolean):[],preservedItems:Array.isArray(report.preservedItems)?report.preservedItems.map(clean).filter(Boolean):[],confidence:clamp(report.confidence),warnings:Array.isArray(report.warnings)?report.warnings.map(clean).filter(Boolean):[]};}
  function normalizeOption(option,context){const brandAttached=hasBrand(context);const diagnostics=[];const raw=inputScore(option);if(!raw)return{score:null,optimizationReport:normalizeReport(option&&option.optimizationReport),scoring:{status:'not_scored',source:'missing',promptVersion:null,diagnostics}};const mapped=mapLegacy(raw);const out={};[...SCORE_KEYS,BRAND_KEY].forEach(k=>{if(k===BRAND_KEY&&!brandAttached)return;const n=clamp(mapped[k]);if(n==null){diagnostics.push(`${k} missing or invalid`);}else{if(Number(mapped[k])!==n)diagnostics.push(`${k} clamped to ${n}`);out[k]=n;}});out.overallScore=clamp(mapped.overallScore);let source='native';if(out.overallScore==null){out.overallScore=computeOverall(out,brandAttached);source='computed-fallback';diagnostics.push('overallScore computed from sub-scores');}
    if(out.overallScore==null)return{score:null,optimizationReport:normalizeReport(option&&option.optimizationReport),scoring:{status:'not_scored',source:'invalid',promptVersion:PROMPT_VERSION,diagnostics}};
    return{score:out,optimizationReport:normalizeReport(option&&option.optimizationReport),scoring:{status:'scored',source,promptVersion:PROMPT_VERSION,diagnostics}};}
  function normalizeOptionInPlace(option,context){const n=normalizeOption(option,context);option.signalScore=n.score;option.optimizationReport=n.optimizationReport;option.scoring=n.scoring;return option;}
  function normalizeResult(result,context){const r=clone(result||{});const ctx={...(context||{}),brandProfile:(context&&context.brandProfile)||r.brandProfile,profileSnapshot:(context&&context.profileSnapshot)||r.profileSnapshot,profileId:(context&&context.profileId)||r.profileId};r.options=(r.options||[]).map(o=>normalizeOptionInPlace(o,ctx));r.diagnostics={...(r.diagnostics||{}),scoring:{promptVersion:PROMPT_VERSION,options:r.options.map(o=>({id:o.id,status:o.scoring&&o.scoring.status,source:o.scoring&&o.scoring.source,validationFailures:(o.scoring&&o.scoring.diagnostics)||[]}))}};return r;}
  function suggestedSlideOrder(slides){return [...(slides||[])].map((s,i)=>({slideId:s.slideId,order:s.order??i,overallScore:(((s.project||{}).optimizationResult||{}).options||[]).find(o=>o.id===(s.project||{}).selectedOptionId)?.signalScore?.overallScore??null})).sort((a,b)=>(b.overallScore??-1)-(a.overallScore??-1)).map((x,i)=>({...x,suggestedOrder:i+1}));}
  function redactDiagnostics(v){return JSON.stringify(v,(k,val)=>typeof val==='string'?SECRET_PATTERNS.reduce((s,re)=>s.replace(re,'[redacted]'),val):val);}
  const api={PROMPT_VERSION,SCORE_KEYS,BRAND_KEY,normalizeOption,normalizeOptionInPlace,normalizeResult,normalizeReport,computeOverall,suggestedSlideOrder,redactDiagnostics};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.SignalScoring=api;
})(typeof window!=='undefined'?window:globalThis);
