(function(root){
  const STATUS={original:'Original',preview:'Preview Ready',package:'AI Package Ready',imported:'Edited Image Imported',export:'Ready for Export'};
  function id(){return`sig_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;}
  function optionState(option){const review=(root.SignalVerification&&root.SignalVerification.createReview)?root.SignalVerification.createReview(option):{preservation:{},operations:{}};return{optionId:option.id,chatGptEditPackage:option.handoff||null,renderedLocalPreview:null,importedEditedImage:null,verification:null,verificationByVersion:{},preservationReview:review.preservation,operationReview:review.operations,exportSettings:{source:'preview',presetId:'original',jpegQuality:.9,filename:`signal-${option.id}-preview.jpg`}};}
  function normalizeOptionLineage(o){if(!o.lineage)o.lineage={parentOptionId:o.parentOptionId||null,rootOptionId:o.rootOptionId||o.id,generationType:o.generationType||'base',variationStrength:o.variationStrength||null,generationIndex:o.generationIndex==null?null:o.generationIndex};return o;}
  function createProject(args){const bp=root.SignalBrandProfiles||(typeof require!=='undefined'?require('./signal-brand-profiles.js'):null);const snap=bp?bp.snapshot(args.brandProfile):{profileId:null,profileVersion:null,profileSnapshot:null};const result=args.result||{};result.options=(result.options||[]).map(normalizeOptionLineage);const options={};(result.options||[]).forEach(o=>{options[o.id]=optionState(o);});return{projectId:args.projectId||id(),createdAt:args.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),storageVersion:2,promptVersion:args.promptVersion||(result&&result.promptVersion)||null,diagnostics:args.diagnostics||null,originalMedia:args.originalMedia||null,optimizationResult:result,selectedOptionId:args.selectedOptionId||(result.options&&result.options[0]&&result.options[0].id)||null,options,exportSettings:{source:'preview'},status:'active',profileId:args.profileId!==undefined?args.profileId:snap.profileId,profileVersion:args.profileVersion!==undefined?args.profileVersion:snap.profileVersion,profileSnapshot:args.profileSnapshot!==undefined?args.profileSnapshot:snap.profileSnapshot};}
  function ensureOption(project,option){project.options=project.options||{};if(!project.options[option.id])project.options[option.id]=optionState(option);return project.options[option.id];}

  function findOption(project,optionId){return ((project.optimizationResult&&project.optimizationResult.options)||[]).find(o=>o.id===optionId)||null;}
  function childrenByParent(project,parentId){return ((project.optimizationResult&&project.optimizationResult.options)||[]).filter(o=>o.lineage&&o.lineage.parentOptionId===parentId).sort((a,b)=>(a.lineage.generationIndex||0)-(b.lineage.generationIndex||0));}
  function childrenByRoot(project,rootId){return ((project.optimizationResult&&project.optimizationResult.options)||[]).filter(o=>o.lineage&&o.lineage.rootOptionId===rootId&&o.lineage.generationType==='more-like-this').sort((a,b)=>(a.lineage.generationIndex||0)-(b.lineage.generationIndex||0));}
  function attachChildren(project,parentId,children){const copy=clone(project);const opts=copy.optimizationResult.options||[];const parent=opts.find(o=>o.id===parentId);if(!parent)throw new Error('Parent option not found');if(parent.lineage&&parent.lineage.generationType==='more-like-this')throw new Error('Grandchildren are not supported');const idx=opts.findIndex(o=>o.id===parentId);const normalized=(children||[]).map((c,i)=>normalizeOptionLineage({...c,parentOptionId:parentId,rootOptionId:(parent.lineage&&parent.lineage.rootOptionId)||parent.rootOptionId||parent.id,generationType:'more-like-this',generationIndex:c.generationIndex==null?i:c.generationIndex}));opts.splice(idx+1+childrenByParent(copy,parentId).length,0,...normalized);normalized.forEach(o=>{copy.options[o.id]=optionState(o);});return touch(copy);}
  function selectChild(project,childId){const child=findOption(project,childId);if(!child||!child.lineage||child.lineage.generationType!=='more-like-this')throw new Error('Child option not found');return setSelectedOption(project,childId);}
  function removeChild(project,childId){const child=findOption(project,childId);if(!child||!child.lineage||child.lineage.generationType!=='more-like-this')throw new Error('Only child options can be removed here');const copy=clone(project);copy.optimizationResult.options=(copy.optimizationResult.options||[]).filter(o=>o.id!==childId);delete copy.options[childId];if(copy.selectedOptionId===childId)copy.selectedOptionId=child.lineage.parentOptionId;return touch(copy);}
  function removeParent(project,parentId,args){if(childrenByParent(project,parentId).length&&!(args&&args.cascadeChildren))throw new Error('Parent has child variants. Confirm cascade deletion to remove parent and children.');const copy=clone(project);const ids=new Set([parentId,...childrenByParent(project,parentId).map(c=>c.id)]);copy.optimizationResult.options=(copy.optimizationResult.options||[]).filter(o=>!ids.has(o.id));ids.forEach(id=>delete copy.options[id]);if(ids.has(copy.selectedOptionId))copy.selectedOptionId=(copy.optimizationResult.options[0]&&copy.optimizationResult.options[0].id)||null;return touch(copy);}

  function selectedOption(project){const opts=(project.optimizationResult&&project.optimizationResult.options)||[];return opts.find(o=>o.id===project.selectedOptionId)||opts[0]||null;}
  function setSelectedOption(project,optionId){return touch({...project,selectedOptionId:optionId});}
  function setBrandProfileForNextRequest(project,profile){const bp=root.SignalBrandProfiles||(typeof require!=='undefined'?require('./signal-brand-profiles.js'):null);const snap=bp?bp.snapshot(profile):{profileId:null,profileVersion:null,profileSnapshot:null};return touch({...clone(project),nextProfileId:snap.profileId,nextProfileVersion:snap.profileVersion,nextProfileSnapshot:snap.profileSnapshot});}
  function attachPreview(project,optionId,preview){const copy=clone(project);const opt=copy.options[optionId]||(copy.options[optionId]={optionId});opt.renderedLocalPreview=preview;return touch(copy);}
  function attachImportedImage(project,optionId,image,verification){const copy=clone(project);const opt=copy.options[optionId]||(copy.options[optionId]={optionId});opt.importedEditedImage={...image,versionId:image.versionId||`imported-${Date.now().toString(36)}`};opt.verification=verification;opt.verificationByVersion={...(opt.verificationByVersion||{}),[opt.importedEditedImage.versionId]:verification};opt.exportSettings={...(opt.exportSettings||{}),source:'imported',filename:`signal-${optionId}-imported.jpg`};return touch(copy);}
  function setPreservationReview(project,optionId,checkId,status){const copy=clone(project);const opt=copy.options[optionId]||(copy.options[optionId]={optionId});opt.preservationReview={...(opt.preservationReview||{}),[checkId]:status};return touch(copy);}
  function setOperationReview(project,optionId,operationId,status){if(root.SignalVerification&&root.SignalVerification.OPERATION_STATUSES&&!root.SignalVerification.OPERATION_STATUSES.includes(status))throw new Error('Invalid operation status');const copy=clone(project);const opt=copy.options[optionId]||(copy.options[optionId]={optionId});opt.operationReview={...(opt.operationReview||{}),[operationId]:status};return touch(copy);}
  function setExportSettings(project,optionId,settings){const copy=clone(project);const opt=copy.options[optionId]||(copy.options[optionId]={optionId});opt.exportSettings={...(opt.exportSettings||{}),...(settings||{})};copy.exportSettings={...(copy.exportSettings||{}),...(settings||{})};return touch(copy);}
  function statusFor(project,optionId){const opt=project&&project.options&&project.options[optionId];if(!opt)return STATUS.original;if(opt.importedEditedImage)return STATUS.imported;if(opt.chatGptEditPackage&&opt.renderedLocalPreview)return STATUS.package;if(opt.renderedLocalPreview)return STATUS.preview;return STATUS.original;}
  function exportSource(project,optionId,source){const opt=project.options&&project.options[optionId]||{};if(source==='original')return{label:'Original',asset:project.originalMedia};if(source==='imported')return{label:'Imported AI Edit',asset:opt.importedEditedImage};return{label:'Local Preview',asset:opt.renderedLocalPreview};}
  function touch(p){p.updatedAt=new Date().toISOString();return p;}function clone(v){return JSON.parse(JSON.stringify(v));}
  const api={STATUS,createProject,ensureOption,normalizeOptionLineage,findOption,childrenByParent,childrenByRoot,attachChildren,selectChild,removeChild,removeParent,selectedOption,setSelectedOption,setBrandProfileForNextRequest,attachPreview,attachImportedImage,setPreservationReview,setOperationReview,setExportSettings,statusFor,exportSource};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.SignalProject=api;
})(typeof window!=='undefined'?window:globalThis);
