(function(root){
  function dims(media){return {width:Number(media&&media.width||media&&media.naturalWidth||0),height:Number(media&&media.height||media&&media.naturalHeight||0)};}
  function orientation(d){if(!d.width||!d.height)return'unknown';return d.width===d.height?'square':(d.width>d.height?'landscape':'portrait');}
  function aspect(d){return d.width&&d.height?d.width/d.height:0;}
  function pct(a,b){return b?Math.abs(a-b)/b:0;}
  function verifyImportedImage(expected,actual,opts){opts=opts||{};const exp=dims(expected),act=dims(actual);const warnings=[];const ratioTolerance=opts.ratioTolerance==null?0.03:opts.ratioTolerance;const dimensionTolerance=opts.dimensionTolerance==null?0.08:opts.dimensionTolerance;const er=aspect(exp),ar=aspect(act);if(exp.width&&act.width&&pct(act.width,exp.width)>dimensionTolerance)warnings.push(`Width differs: expected ${exp.width}px, got ${act.width}px.`);if(exp.height&&act.height&&pct(act.height,exp.height)>dimensionTolerance)warnings.push(`Height differs: expected ${exp.height}px, got ${act.height}px.`);if(er&&ar&&Math.abs(ar-er)>ratioTolerance)warnings.push(`Aspect ratio differs: expected ${formatRatio(er)}, got ${formatRatio(ar)}.`);if(orientation(exp)!==orientation(act)&&orientation(exp)!=='unknown'&&orientation(act)!=='unknown')warnings.push(`Orientation differs: expected ${orientation(exp)}, got ${orientation(act)}.`);return{ok:warnings.length===0,warnings,expected:{...exp,aspectRatio:er,orientation:orientation(exp)},actual:{...act,aspectRatio:ar,orientation:orientation(act)}};}
  function formatRatio(r){return Number.isFinite(r)&&r?`${r.toFixed(3)}:1`:'unknown';}
  function sourceFor(project,optionId,source){const opt=project&&project.options&&project.options[optionId]||{};if(source==='original')return{label:'Original',dataUrl:project.originalMedia&&project.originalMedia.dataUrl,meta:project.originalMedia};if(source==='imported')return{label:'Imported AI Edit',dataUrl:opt.importedEditedImage&&opt.importedEditedImage.dataUrl,meta:opt.importedEditedImage};return{label:'Local Preview',dataUrl:opt.renderedLocalPreview&&opt.renderedLocalPreview.dataUrl,meta:opt.renderedLocalPreview};}
  const api={verifyImportedImage,sourceFor,orientation,aspect};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.SignalCompare=api;
})(typeof window!=='undefined'?window:globalThis);
