const assert=require('assert');
const SignalCarousel=require('../signal-carousel.js');
const SignalProject=require('../signal-project.js');
const SignalStorage=require('../signal-storage.js');
const SignalPromptBuilder=require('../signal-prompt-builder.js');
function memoryStorage(){const m=new Map();return{getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}}
function result(id,w=1080,h=1350,caption='premium service',tags=['#premium']){return{schemaVersion:'2.0',promptVersion:'signal-v2.3-carousel',contentType:'image',platform:'instagram',format:{name:'Feed',aspectRatio:'4:5',width:w,height:h},subject:{description:id,preserve:[]},options:[{id:'base',name:id,description:id,output:{width:w,height:h,aspectRatio:'4:5'},localAdjustments:[{operation:'crop',value:{x:id},target:'full'}],handoff:null}],captions:[{text:caption}],hashtags:{recommended:tags}}}
const profile={id:'bp',version:1,name:'Premium',brandVoice:{keywords:['premium']},aiDefaults:{defaultOptionCount:2,allowCreativeTransformations:false}};
let carousel=SignalCarousel.createCarousel({brandProfile:profile,slides:[{result:result('hook'),originalMedia:{name:'1.jpg',width:1200,height:1500}},{result:result('detail'),originalMedia:{name:'2.jpg',width:1200,height:1500}}]});
assert.equal(carousel.projectType,'carousel','carousel creation marks project type');
assert.equal(carousel.slides.length,2,'carousel creation stores slides');
assert.ok(carousel.slides.every(s=>s.project.profileSnapshot&&s.project.profileSnapshot.id==='bp'),'Brand Profile snapshot applies to all slides');
carousel=SignalCarousel.addSlide(carousel,{result:result('proof'),originalMedia:{name:'3.jpg'}});
assert.equal(carousel.slides.length,3,'slide addition works');
const first=carousel.slides[0].slideId, third=carousel.slides[2].slideId;
carousel=SignalCarousel.updateSlideProject(carousel,first,p=>SignalProject.attachChildren(p,'base',[{id:'v1',name:'Variant',description:'variant',output:{width:1080,height:1350},localAdjustments:[]} ]));
carousel=SignalCarousel.updateSlideProject(carousel,third,p=>SignalProject.setExportSettings(p,'base',{filename:'custom-proof.jpg'}));
carousel=SignalCarousel.moveSlide(carousel,third,0);
carousel=SignalCarousel.moveSlideDown(carousel,third);
carousel=SignalCarousel.moveSlideUp(carousel,third);
carousel=SignalCarousel.dragDropReorder(carousel,third,carousel.slides[0].slideId);
assert.equal(carousel.slides[0].slideId,third,'reordering moves slide');
assert.equal(carousel.slides.find(s=>s.slideId===first).project.optimizationResult.options.length,2,'reordering preserves per-slide variants');
assert.equal(carousel.slides[0].project.options.base.exportSettings.filename,'custom-proof.jpg','reordering preserves export state');
carousel=SignalCarousel.removeSlide(carousel,carousel.slides[1].slideId);
assert.equal(carousel.slides.length,2,'slide removal works');
let bad=SignalCarousel.addSlide(carousel,{result:result('bad',1000,1000,'off brand',[])});
const review=SignalCarousel.verifyCarousel(bad);
assert.ok(review.blocked&&review.issues.some(i=>i.code==='carousel_dimensions'),'cross-slide verification catches dimension mismatch');
assert.ok(review.issues.some(i=>i.code==='caption_branding'),'cross-slide verification catches caption/branding inconsistency');
const slideExport=SignalCarousel.exportSlide(carousel,carousel.slides[0].slideId);
assert.equal(slideExport.name,'custom-proof.jpg','individual slide export reuses per-option export setting');
const pkg=SignalCarousel.exportPackage(carousel);
assert.equal(pkg.approach,'sequential-downloads','full export package documents sequential-download approach');
assert.ok(pkg.files.some(f=>f.name==='manifest.json'),'package includes manifest');
assert.ok(pkg.files.some(f=>f.name==='captions.txt'),'package includes captions');
assert.ok(pkg.files.some(f=>f.name==='hashtags.txt'),'package includes hashtags');
assert.ok(pkg.files.filter(f=>f.type==='image')[0].name.startsWith('01-'),'package includes numbered image files');
const storage=memoryStorage();SignalStorage.saveProject(carousel,storage);const reloaded=SignalStorage.loadProject(carousel.projectId,storage);
assert.equal(reloaded.slides.length,2,'browser reload recovery persists carousel slides');
const backup=SignalStorage.exportProjectPackage(carousel.projectId,storage,{getAsset:async()=>null});
Promise.resolve(backup).then(async pkg=>{const restored=await SignalStorage.restoreProjectPackage(pkg,memoryStorage(),{putAsset:async a=>a});assert.equal(restored.projectType,'carousel','backup/restore keeps carousel type');const single=SignalProject.createProject({result:result('single')});SignalStorage.saveProject(single,storage);assert.notEqual(SignalStorage.loadProject(single.projectId,storage).projectType,'carousel','single-image compatibility remains untouched');const ctx=SignalPromptBuilder.buildCarouselRequestContext({brandProfile:profile,slides:carousel.slides});assert.equal(ctx.promptVersion,'signal-v2.3-carousel','carousel prompt version is used');assert.equal(ctx.totalSlideCount,2,'prompt includes total slide count');assert.ok(ctx.currentSlideOrdering[0].roleHint,'prompt includes slide role hints');console.log('signal carousel tests passed');}).catch(e=>{console.error(e);process.exit(1);});
