const assert=require('assert');
global.SignalPromptBuilder=require('../signal-prompt-builder.js');
global.SignalContract=require('../signal-contract.js');
const V=require('../signal-variant-generator.js');
const Project=require('../signal-project.js');
const Storage=require('../signal-storage.js');
function memoryStorage(){const m=new Map();return{getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}}
const parent={id:'premium',name:'Premium',description:'Refined premium product image with controlled reflections.',status:'readyNow',risk:'low',output:{width:1080,height:1350,aspectRatio:'4:5',mimeType:'image/jpeg'},localAdjustments:[{operation:'crop',value:{x:.5,y:.5,scale:1},target:'full media'},{operation:'contrast',value:5,target:'full media'}],generativeOperations:[],preservationRules:['identity','geometry','colors','branding','reflections'],score:{overall:80,composition:80,platformFit:80,technicalQuality:80,subjectPreservation:95,generativeConfidence:90}};
const result={schemaVersion:'2.0',promptVersion:'signal-v2.1-photo',contentType:'image',platform:'instagram',format:{name:'Feed',aspectRatio:'4:5',width:1080,height:1350},subject:{type:'product',description:'bottle',preserve:['identity']},options:[parent],captions:[],hashtags:{recommended:[]}};
function child(name,extra={}){return Object.assign({},parent,{id:name.toLowerCase(),name:`Premium — ${name}`,description:name==='Warmer'?'Warmer balanced color temperature for a gentle premium finish.':name==='Tighter'?'Closer crop with stronger subject scale for feed impact.':'Soft edge falloff with calmer contrast and separation.',localAdjustments:[...parent.localAdjustments,{operation:name==='Warmer'?'whiteBalance':name==='Tighter'?'crop':'vignette',value:name,target:'full media'}],generativeOperations:[],},extra)}
(async()=>{
  const prompt=global.SignalPromptBuilder.buildVariantPrompt({parentOption:parent,variationStrength:'moderate',selectedPlatform:'instagram',sourceDimensions:{width:1200,height:1600}});assert.equal(prompt.promptVersion,V.PROMPT_VERSION);assert.ok(prompt.userText.includes(parent.id)&&prompt.userText.includes('Moderate'));
  let local=V.localVariants(parent,{variationStrength:'subtle'});assert.equal(local.ok,true);assert.equal(local.children.length,3);assert.ok(local.children.every(c=>c.variantSource==='local-only'&&c.lineage.parentOptionId==='premium'));
  const genParent={...parent,generativeOperations:[{operation:'removeObject',instruction:'remove cup'}]};assert.equal(V.canGenerateLocal(genParent,'subtle'),false,'generative parents cannot use local-only');
  let checked=V.validateAndDedupe([parent,child('Warmer'),child('Warmer')],parent,'subtle',{pipelineResult:'ai',model:'m'});assert.equal(checked.ok,false);assert.ok(checked.rejections.length>=2,'rejects parent-identical and duplicate children');
  checked=V.validateAndDedupe([child('Warmer'),child('Tighter'),child('Softer',{localAdjustments:[...parent.localAdjustments,{operation:'vignette',value:-.1,target:'full media'}]})],parent,'moderate',{pipelineResult:'ai',model:'m'});assert.equal(checked.ok,true,'partial or full valid batch accepted with at least two');
  const subtleBad=V.validateAndDedupe([child('AI',{generativeOperations:[{operation:'removeObject'}]}),child('Tighter')],parent,'subtle',{});assert.ok(subtleBad.rejections.some(r=>String(r.errors).includes('generative')),'subtle generative transformations rejected');
  let project=Project.createProject({result});const before=JSON.stringify(project.options.premium);project=Project.attachChildren(project,'premium',local.children);assert.equal(Project.childrenByParent(project,'premium').length,3);assert.equal(Project.childrenByRoot(project,'premium').length,3);assert.equal(JSON.stringify(project.options.premium),before,'parent state unchanged');assert.throws(()=>Project.attachChildren(project,local.children[0].id,[child('Grand')]),/Grandchildren/);project=Project.selectChild(project,local.children[1].id);assert.equal(project.selectedOptionId,local.children[1].id);project=Project.attachImportedImage(project,local.children[1].id,{name:'edit.jpg',dataUrl:'data:x',width:1,height:1},{ok:true});assert.equal(project.options[local.children[1].id].importedEditedImage.name,'edit.jpg');assert.equal(project.options.premium.importedEditedImage,null,'child imported asset independent');project=Project.setExportSettings(project,local.children[1].id,{source:'imported',presetId:'square'});assert.notEqual((project.options.premium.exportSettings||{}).presetId,'square');assert.throws(()=>Project.removeParent(project,'premium'),/Confirm cascade/,'parent deletion requires explicit cascade');project=Project.removeChild(project,local.children[1].id);assert.equal(Project.childrenByParent(project,'premium').length,2);assert.equal(project.selectedOptionId,'premium');
  const storage=memoryStorage();Storage.saveProject(project,storage);const reloaded=Storage.loadProject(project.projectId,storage);assert.equal(Project.childrenByParent(reloaded,'premium').length,2,'children survive reload');const pkg=await Storage.exportProjectPackage(project.projectId,storage,{getAsset:async()=>null});const restored=await Storage.restoreProjectPackage(pkg,storage,{putAsset:async a=>a});assert.equal(Project.childrenByParent(restored,'premium').length,2,'children survive backup restore');
  let calls=0;const native={schemaVersion:'2.0',promptVersion:V.PROMPT_VERSION,contentType:'image',platform:'instagram',format:result.format,subject:result.subject,options:[child('Warmer'),child('Tighter')],captions:[],hashtags:{recommended:[]},security:{retainOriginal:true,stripMetadataOnExport:true,sendOnlyRequiredMedia:true,prohibitedData:['credentials']}};const fetchImpl=async()=>{calls++;return{ok:true,status:200,json:async()=>({content:[{type:'text',text:JSON.stringify(native)}]})}};const ai=await V.generateAI({apiKey:'sk',model:'m',fetchImpl,parentOption:parent,variationStrength:'moderate'});assert.equal(ai.children.length,2);assert.equal(ai.diagnostics.promptVersion,V.PROMPT_VERSION);assert.equal(calls,1);await assert.rejects(V.generateAI({model:'m',fetchImpl,parentOption:parent,variationStrength:'moderate'}),/API key/);
  const red=JSON.stringify(V.diagnostics({parentOptionId:'p',variationStrength:'subtle',localVsAI:'ai',apiKey:'sk-secret',mediaContent:'data:image'}));assert.ok(!red.includes('sk-secret')&&!red.includes('data:image'),'diagnostics contain no secrets/media');
  console.log('signal more-like-this tests passed');
})().catch(e=>{console.error(e);process.exit(1);});
