const assert=require('assert');
const SignalProject=require('../signal-project.js');
const SignalStorage=require('../signal-storage.js');
const SignalCompare=require('../signal-compare.js');
function memoryStorage(){const m=new Map();return{getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}}
const result={schemaVersion:'2.0',contentType:'image',platform:'instagram',format:{name:'Feed',aspectRatio:'4:5',width:1080,height:1350},subject:{description:'car',preserve:['car']},options:[{id:'clean',name:'Clean',output:{width:1080,height:1350,aspectRatio:'4:5'},handoff:null},{id:'premium',name:'Premium',output:{width:1080,height:1350,aspectRatio:'4:5'},handoff:{editor:'chatgpt',prompt:'Edit premium'}}]};
const storage=memoryStorage();
let project=SignalProject.createProject({result,originalMedia:{name:'orig.jpg',width:1200,height:1500,dataUrl:'data:orig'}});
assert.ok(project.projectId,'project creation assigns id');
assert.equal(project.selectedOptionId,'clean','project creation selects first option');
project=SignalProject.setSelectedOption(project,'premium');
SignalStorage.saveProject(project,storage);
assert.equal(SignalStorage.getActiveProject(storage).selectedOptionId,'premium','selected option persists on reload');
let reloaded=SignalStorage.loadProject(project.projectId,storage);
assert.equal(reloaded.options.premium.chatGptEditPackage.prompt,'Edit premium','ChatGPT package stays with originating option');
const verification=SignalCompare.verifyImportedImage({width:1080,height:1350},{width:1080,height:1350});
reloaded=SignalProject.attachImportedImage(reloaded,'premium',{name:'edit.jpg',width:1080,height:1350,dataUrl:'data:edit'},verification);
assert.equal(SignalProject.statusFor(reloaded,'premium'),'Edited Image Imported','edited image import updates status');
assert.equal(SignalProject.statusFor(reloaded,'clean'),'Original','other option remains independent');
assert.equal(SignalProject.exportSource(reloaded,'premium','imported').label,'Imported AI Edit','export source selection identifies imported edit');
const bad=SignalCompare.verifyImportedImage({width:1080,height:1350},{width:1920,height:1080});
assert.ok(!bad.ok&&bad.warnings.some(w=>w.includes('Orientation')),'comparison logic warns on substantial mismatch');
SignalStorage.saveProject(reloaded,storage);
const second=SignalProject.createProject({result,projectId:'second',originalMedia:{name:'second.jpg'}});
SignalStorage.saveProject(second,storage);
assert.equal(SignalStorage.listProjects(storage).length,2,'multiple simultaneous projects persist');
const migrated=SignalStorage._migrate({projectId:'legacy-one',selectedOptionId:'clean'});
assert.equal(migrated.version,SignalStorage.VERSION,'local storage migration versions legacy data');
storage.setItem(SignalStorage.KEY,'{corrupt');
assert.doesNotThrow(()=>SignalStorage.recover(storage),'corrupted project recovery does not throw');
console.log('signal project workflow tests passed');
