const assert=require('assert');
const SignalContract=require('../signal-contract.js');
const SignalOptionsUI=require('../signal-options-ui.js');
const option={id:'clean',name:'Clean',description:'Finished clean correction.',status:'readyNow',risk:'low',output:{width:1080,height:1350,aspectRatio:'4:5'},localAdjustments:[{operation:'crop',value:'4:5',target:'full media'}],generativeOperations:[],preservationRules:['preserve vehicle'],score:{overall:82,composition:80,platformFit:83,technicalQuality:78,subjectPreservation:95,generativeConfidence:90}};
const result={schemaVersion:'2.0',contentType:'image',platform:'instagram',format:{name:'Instagram Feed',aspectRatio:'4:5',width:1080,height:1350},subject:{type:'vehicle',description:'vehicle',preserve:['paint']},options:[option,{...option,id:'premium',name:'Premium',description:'Premium finish.',risk:'medium',generativeOperations:[{operation:'reduceGlare',instruction:'Reduce glare safely.',targets:['glare'],reconstruction:'Blend surfaces.',preserve:['paint']}],handoff:{editor:'chatgpt',prompt:'Make the premium finished version.',expectedOutput:'One finished media asset, not advice.'},score:{...option.score,overall:88}}],captions:[{text:'Polished and ready.',tone:'premium',callToAction:null}],hashtags:{recommended:['#cars'],avoid:[]}};
const html=SignalOptionsUI.render(result,{selectedOptionId:'premium'});
assert.ok(html.includes('Premium'),'option rendering includes selected option');
assert.ok(html.includes('1080×1350'),'option rendering includes dimensions');
assert.ok(html.includes('AI Enhancement'),'AI enhancement section renders');
assert.ok(html.includes('Make the premium finished version.'),'handoff prompt renders');
assert.ok(html.includes('Polished and ready.'),'captions render');
assert.ok(html.includes('#cars'),'hashtags render');
assert.equal(SignalOptionsUI.selectedOption(result,'premium').name,'Premium','option selection works');
const legacy={category:'vehicle',contentType:'photo',cropFocus:{x:.4,y:.5},instagram:{overall:4,scores:{hook:4,pacing:null,completion:null,trendFit:4,audio:null,textOverlay:3,shareability:4,saveWorthiness:4,originality:3,caption:4}},tiktok:null,topFixes:[],idealVersion:'',hashtags:{instagram:['#cars'],tiktok:[]},captions:['Legacy caption'],cleanupInstructions:'Remove clutter while preserving the car.',videoEdit:''};
const adapted=SignalContract.parseValidateNormalizeOptimizationResult(JSON.stringify(legacy));
assert.ok(SignalOptionsUI.render(adapted).includes('Clean'),'legacy adapter rendering includes options');
assert.ok(SignalOptionsUI.render({options:[]}).includes("couldn't confidently generate"),'empty options state renders');
let threw=false;const oldError=console.error;console.error=()=>{};try{SignalContract.parseValidateNormalizeOptimizationResult(JSON.stringify({...result,options:[option]}));}catch(e){threw=true;}console.error=oldError;assert.ok(threw,'invalid option counts are rejected');
assert.equal(SignalOptionsUI.progressLabel('reading'),'Analyzing composition…');
assert.equal(SignalOptionsUI.progressLabel('analyzing'),'Building optimization options…');
assert.equal(SignalOptionsUI.progressLabel('preparing'),'Preparing previews…');
assert.equal(SignalOptionsUI.progressLabel('finalizing'),'Finalizing results…');
console.log('signal-options-ui tests passed');
