const assert=require('assert');
const fs=require('fs');
const path=require('path');
global.SignalContract=require('../signal-contract.js');
global.SignalPromptBuilder=require('../signal-prompt-builder.js');
const AI=require('../signal-ai-client.js');
const Prompt=require('../signal-prompt-builder.js');
const Contract=require('../signal-contract.js');
function option(id,name,ops=[{operation:'crop',value:'4:5',target:'full media'}],desc){return{id,name,description:desc||`${name} finished platform-ready outcome.`,status:'readyNow',risk:'low',output:{width:id==='story'?1080:1080,height:id==='story'?1920:1350,aspectRatio:id==='story'?'9:16':'4:5',mimeType:'image/jpeg'},localAdjustments:ops,generativeOperations:[],preservationRules:['identity','geometry','colors','branding','reflections'],approvalReason:null,handoff:null,score:{overall:80,composition:78,platformFit:82,technicalQuality:79,subjectPreservation:95,generativeConfidence:88,disclaimer:'Directional score comparing Signal options; not a promise of engagement or revenue.'}}}
function native(){return{schemaVersion:'2.0',promptVersion:Prompt.PROMPT_VERSION,contentType:'image',platform:'instagram',format:{name:'Instagram Feed',aspectRatio:'4:5',width:1080,height:1350},subject:{type:'product',description:'blue bottle',preserve:['identity','geometry','colors']},options:[option('clean','Clean',[{operation:'crop',value:'4:5',target:'full media'},{operation:'contrast',value:6,target:'full media'}],'Clean corrected product image.'),option('story','Story Fit',[{operation:'blurredBackdrop',value:true,target:'background'},{operation:'resize',value:{width:1080,height:1920},target:'full media'}],'Vertical story-ready version with soft backdrop.')],captions:[{text:'Small detail, big signal.',tone:'clean',callToAction:null}],hashtags:{recommended:['#design'],avoid:['#fyp']},security:{retainOriginal:true,stripMetadataOnExport:true,sendOnlyRequiredMedia:true,prohibitedData:['credentials']}}}
function response(obj){return{content:[{type:'text',text:typeof obj==='string'?obj:JSON.stringify(obj)}]};}
function fetchSeq(items){let i=0;const calls=[];const f=async(url,opts)=>{calls.push({url,opts});return{ok:true,status:200,json:async()=>response(items[i++])};};f.calls=calls;return f;}
async function mustReject(p,msg){let ok=false;try{await p;}catch(e){ok=true;}assert.ok(ok,msg);}
(async()=>{
  let f=fetchSeq([native()]);let out=await AI.optimize({apiKey:'sk-ant-secret',model:'claude-test',fetchImpl:f,mediaContent:[],mediaType:'image',selectedPlatform:'instagram',sourceDimensions:{width:1200,height:1600}});assert.equal(out.diagnostics.parsingResult,'native V2');assert.equal(out.result.promptVersion,Prompt.PROMPT_VERSION);const requestBody=JSON.parse(f.calls[0].opts.body);assert.equal(requestBody.max_tokens,8000,'optimization requests allow enough output tokens');assert.ok(requestBody.system.includes('compact JSON')&&requestBody.system.includes('Do not restate'),'prompt limits response verbosity');
  f=fetchSeq(['```json\n'+JSON.stringify(native())+'\n```',native()]);out=await AI.optimize({apiKey:'sk-ant-secret',model:'claude-test',fetchImpl:f,mediaContent:[],mediaType:'image'});assert.equal(out.diagnostics.parsingResult,'repaired native V2','fenced response is rejected then repaired');assert.equal(out.diagnostics.retryCount,1);

  const driftRaw=fs.readFileSync(path.join(__dirname,'fixtures','anthropic-schema-drift-response.json'),'utf8');
  f=fetchSeq([driftRaw]);out=await AI.optimize({apiKey:'sk-ant-secret',model:'claude-test',fetchImpl:f,mediaContent:[],mediaType:'image',selectedPlatform:'instagram',sourceDimensions:{width:1080,height:1350}});assert.equal(out.diagnostics.parsingResult,'native V2');assert.equal(out.result.options[0].id,'opt-1');assert.equal(out.result.platform,'instagram');
  f=fetchSeq(['not json','still not json']);await AI.optimize({apiKey:'sk-ant-secret',model:'claude-test',fetchImpl:f,mediaContent:[],mediaType:'image'}).then(()=>assert.fail('invalid JSON should reject'),e=>assert.equal(e.category,'invalid-json'));
  const truncatedRaw=fs.readFileSync(path.join(__dirname,'fixtures','anthropic-truncated-response.json'),'utf8');f=fetchSeq([truncatedRaw,truncatedRaw]);await AI.optimize({apiKey:'sk-ant-secret',model:'claude-test',fetchImpl:f,mediaContent:[],mediaType:'image'}).then(()=>assert.fail('truncated JSON should reject'),e=>{assert.equal(e.category,'truncated-response');assert.equal(e.message,"Anthropic's response was cut off before finishing. Try again, or contact support if this keeps happening.");});

  f=fetchSeq(['not json','still not json']);await mustReject(AI.optimize({apiKey:'sk-ant-secret',model:'claude-test',fetchImpl:f,mediaContent:[],mediaType:'image'}),'repair failure rejects');assert.equal(f.calls.length,2,'retry limit is one repair');
  const dup=native();dup.options=[option('a','Same'),option('b','Same')];assert.ok(!Contract.validateSemanticDiversity(dup).valid,'duplicate-option detection');f=fetchSeq([dup,native()]);out=await AI.optimize({apiKey:'sk-ant-secret',model:'claude-test',fetchImpl:f,mediaContent:[],mediaType:'image'});assert.ok(out.diagnostics.diversityCheckFailures.length,'diversity failure tracked');

  const nearMiss=native();nearMiss.subject.boundingBoxes=[{x:0.1,y:0.2,w:0.3,h:0.4},[0.2,0.3,0.2,0.2]];nearMiss.captions='Small detail, big signal.';nearMiss.hashtags.recommended='#design #studio';const repaired=native();repaired.subject.boundingBoxes=[{x:0.1,y:0.2,width:0.3,height:0.4,units:'normalized'},{x:0.2,y:0.3,width:0.2,height:0.2,units:'normalized'}];f=fetchSeq([nearMiss,repaired]);out=await AI.optimize({apiKey:'sk-ant-secret',model:'claude-test',fetchImpl:f,mediaContent:[],mediaType:'image'});assert.equal(out.diagnostics.parsingResult,'repaired native V2','repair recovers captions and hashtags shape mismatches');assert.equal(out.result.subject.boundingBoxes.length,2);assert.ok(f.calls[1].opts.body.includes('captions must be an array'),'repair prompt includes caption shape guidance');assert.ok(f.calls[1].opts.body.includes('hashtags.recommended must be an array'),'repair prompt includes hashtag shape guidance');

  const perOptionRaw=fs.readFileSync(path.join(__dirname,'fixtures','anthropic-per-option-captions-response.json'),'utf8');const direct=Contract.parseStrictNativeV2(perOptionRaw,{selectedPlatform:'instagram',selectedFormat:{name:'Instagram Feed',aspectRatio:'4:5',width:1080,height:1350},mediaType:'image'});const progress=[];f=fetchSeq(['not json',perOptionRaw]);out=await AI.optimize({apiKey:'sk-ant-secret',model:'claude-test',fetchImpl:f,mediaContent:[],mediaType:'image',selectedPlatform:'instagram',selectedFormat:{name:'Instagram Feed',aspectRatio:'4:5',width:1080,height:1350},onProgress:s=>progress.push(s)});assert.deepEqual(out.result.options.map(o=>o.captions),direct.options.map(o=>o.captions),'repair uses identical extraction, normalization, and validation');assert.ok(progress.includes('Waiting for Claude…')&&progress.includes('Retrying with Claude…')&&progress.includes('Validating response…'),'primary and repair stages report progress');

  const bad=native();bad.options[0].description='Reshoot from a better angle.';assert.ok(!Contract.validateOptimizationResult(bad).valid,'prohibited recommendation detection');
  const legacy={category:'thing',contentType:'photo',cropFocus:{x:.5,y:.5},instagram:{overall:4,scores:{}},tiktok:null,topFixes:[{fix:'Clean',why:'Clutter'}],idealVersion:'Done',hashtags:{instagram:['#x'],tiktok:[]},captions:['Done'],cleanupInstructions:'Remove clutter while preserving subject.',videoEdit:''};f=fetchSeq([legacy,'bad']);out=await AI.optimize({apiKey:'sk-ant-secret',model:'claude-test',fetchImpl:f,mediaContent:[],mediaType:'image'});assert.equal(out.diagnostics.parsingResult,'legacy adapted');assert.equal(out.diagnostics.legacyFallbackUsed,true);

  await AI.optimize({apiKey:'',model:'claude-test',fetchImpl:async()=>{throw new Error('no call')},mediaContent:[],mediaType:'image'}).then(()=>assert.fail('missing key should reject'),e=>assert.equal(e.category,'missing-api-key'));
  await AI.optimize({apiKey:'sk-ant-bad',model:'claude-test',fetchImpl:async()=>({ok:false,status:401,json:async()=>({})}),mediaContent:[],mediaType:'image'}).then(()=>assert.fail('invalid key should reject'),e=>assert.equal(e.category,'invalid-api-key'));
  await AI.optimize({apiKey:'sk-ant-x',model:'claude-test',fetchImpl:async()=>{throw new Error('offline')},mediaContent:[],mediaType:'image'}).then(()=>assert.fail('network should reject'),e=>assert.equal(e.category,'network'));
  const missing=native();delete missing.options[0].output;f=fetchSeq([missing,missing]);await AI.optimize({apiKey:'sk-ant-secret',model:'claude-test',fetchImpl:f,mediaContent:[],mediaType:'image'}).then(()=>assert.fail('schema should reject'),e=>{assert.equal(e.category,'schema-validation');assert.ok(e.message.includes('options[0].output'));});

  const ctx=Prompt.buildRequestContext({selectedPlatform:'tiktok',selectedFormat:{name:'TikTok',aspectRatio:'9:16',width:1080,height:1920},sourceDimensions:{width:720,height:1280},mediaType:'video'});assert.equal(ctx.selectedPlatform,'tiktok');assert.equal(ctx.selectedFormat.aspectRatio,'9:16');assert.ok(ctx.supportedLocalRendererOperations.includes('crop'));
  const red=AI.redact({apiKey:'sk-ant-secret',authorization:'Bearer abc',raw:'token=secret sk-ant-secret',data:'base64'});assert.ok(!red.includes('sk-ant-secret')&&!red.includes('Bearer abc')&&!red.includes('base64'),'key and diagnostics redaction');
  console.log('signal-ai-client tests passed');
})().catch(e=>{console.error(e);process.exit(1);});
