const assert=require('assert');
global.SignalContract=require('../signal-contract.js');
global.SignalPromptBuilder=require('../signal-prompt-builder.js');
const AI=require('../signal-ai-client.js');
const Prompt=require('../signal-prompt-builder.js');
const Contract=require('../signal-contract.js');
function option(id,name,ops=[{operation:'crop',value:'4:5',target:'full media'}],desc){return{id,name,description:desc||`${name} finished platform-ready outcome.`,status:'readyNow',risk:'low',output:{width:id==='story'?1080:1080,height:id==='story'?1920:1350,aspectRatio:id==='story'?'9:16':'4:5',mimeType:'image/jpeg'},localAdjustments:ops,generativeOperations:[],preservationRules:['identity','geometry','colors','branding','reflections'],approvalReason:null,handoff:null,score:{overall:80,composition:78,platformFit:82,technicalQuality:79,subjectPreservation:95,generativeConfidence:88,disclaimer:'Directional score comparing Signal options; not a promise of engagement or revenue.'}}}
function native(){return{schemaVersion:'2.0',promptVersion:Prompt.PROMPT_VERSION,contentType:'image',platform:'instagram',format:{name:'Instagram Feed',aspectRatio:'4:5',width:1080,height:1350},subject:{type:'product',description:'blue bottle',preserve:['identity','geometry','colors']},options:[option('clean','Clean',[{operation:'crop',value:'4:5',target:'full media'},{operation:'contrast',value:6,target:'full media'}],'Clean corrected product image.'),option('story','Story Fit',[{operation:'blurredBackdrop',value:true,target:'background'},{operation:'resize',value:{width:1080,height:1920},target:'full media'}],'Vertical story-ready version with soft backdrop.')],captions:[{text:'Small detail, big signal.',tone:'clean',callToAction:null}],hashtags:{recommended:['#design'],avoid:['#fyp']},security:{retainOriginal:true,stripMetadataOnExport:true,sendOnlyRequiredMedia:true,prohibitedData:['credentials']}}}
function response(obj){return{content:[{type:'text',text:typeof obj==='string'?obj:JSON.stringify(obj)}]};}
function fetchSeq(items){let i=0;const calls=[];const f=async(url,opts)=>{calls.push({url,opts});return{ok:true,status:200,json:async()=>response(items[i++])};};f.calls=calls;return f;}
async function mustReject(p,msg){let ok=false;try{await p;}catch(e){ok=true;}assert.ok(ok,msg);}
(async()=>{
  let f=fetchSeq([native()]);let out=await AI.optimize({apiKey:'sk-ant-secret',model:'claude-test',fetchImpl:f,mediaContent:[],mediaType:'image',selectedPlatform:'instagram',sourceDimensions:{width:1200,height:1600}});assert.equal(out.diagnostics.parsingResult,'native V2');assert.equal(out.result.promptVersion,Prompt.PROMPT_VERSION);
  f=fetchSeq(['```json\n'+JSON.stringify(native())+'\n```',native()]);out=await AI.optimize({apiKey:'sk-ant-secret',model:'claude-test',fetchImpl:f,mediaContent:[],mediaType:'image'});assert.equal(out.diagnostics.parsingResult,'repaired native V2','fenced response is rejected then repaired');assert.equal(out.diagnostics.retryCount,1);
  f=fetchSeq(['not json','still not json']);await mustReject(AI.optimize({apiKey:'sk-ant-secret',model:'claude-test',fetchImpl:f,mediaContent:[],mediaType:'image'}),'repair failure rejects');assert.equal(f.calls.length,2,'retry limit is one repair');
  const dup=native();dup.options=[option('a','Same'),option('b','Same')];assert.ok(!Contract.validateSemanticDiversity(dup).valid,'duplicate-option detection');f=fetchSeq([dup,native()]);out=await AI.optimize({apiKey:'sk-ant-secret',model:'claude-test',fetchImpl:f,mediaContent:[],mediaType:'image'});assert.ok(out.diagnostics.diversityCheckFailures.length,'diversity failure tracked');
  const bad=native();bad.options[0].description='Reshoot from a better angle.';assert.ok(!Contract.validateOptimizationResult(bad).valid,'prohibited recommendation detection');
  const legacy={category:'thing',contentType:'photo',cropFocus:{x:.5,y:.5},instagram:{overall:4,scores:{}},tiktok:null,topFixes:[{fix:'Clean',why:'Clutter'}],idealVersion:'Done',hashtags:{instagram:['#x'],tiktok:[]},captions:['Done'],cleanupInstructions:'Remove clutter while preserving subject.',videoEdit:''};f=fetchSeq([legacy,'bad']);out=await AI.optimize({apiKey:'sk-ant-secret',model:'claude-test',fetchImpl:f,mediaContent:[],mediaType:'image'});assert.equal(out.diagnostics.parsingResult,'legacy adapted');assert.equal(out.diagnostics.legacyFallbackUsed,true);
  const ctx=Prompt.buildRequestContext({selectedPlatform:'tiktok',selectedFormat:{name:'TikTok',aspectRatio:'9:16',width:1080,height:1920},sourceDimensions:{width:720,height:1280},mediaType:'video'});assert.equal(ctx.selectedPlatform,'tiktok');assert.equal(ctx.selectedFormat.aspectRatio,'9:16');assert.ok(ctx.supportedLocalRendererOperations.includes('crop'));
  const red=AI.redact({apiKey:'sk-ant-secret',authorization:'Bearer abc',raw:'token=secret sk-ant-secret',data:'base64'});assert.ok(!red.includes('sk-ant-secret')&&!red.includes('Bearer abc')&&!red.includes('base64'),'key and diagnostics redaction');
  console.log('signal-ai-client tests passed');
})().catch(e=>{console.error(e);process.exit(1);});
